name: Trigger auto deployment for container-app-izvij5ukdq6ro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-izvij5ukdq6ro-AutoDeployTrigger-cf9cdd63-8745-4946-93ec-a793525826b9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPIZVIJ5UKDQ6RO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPIZVIJ5UKDQ6RO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPIZVIJ5UKDQ6RO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPIZVIJ5UKDQ6RO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPIZVIJ5UKDQ6RO_REGISTRY_PASSWORD }}
          containerAppName: container-app-izvij5ukdq6ro
          resourceGroup: todonodejspgsqlgoogleauth872c80e8
          imageToBuild: default/container-app-izvij5ukdq6ro:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


